#!/bin/bash

echo -e "\e[31mubuntu-update.sh Copyright (C) 2018 Ted LeRoy"
echo -e "This program comes with ABSOLUTELY NO WARRANTY' see "
echo -e "https://github.com/TedLeRoy/ubuntu-update.sh/blob/master/LICENSE.md"
echo -e "This is free software, and you are welcome to redistribute it"
echo -e "under certain conditions."
echo -e "Again, see  https://github.com/TedLeRoy/ubuntu-update.sh/blob/master/LICENSE.md"
echo -e "for details.\e[0m"

# The -e "\32m...\e[0m" code is to display output in color.

echo ""
echo ""
echo -e "\e[32m#############################"
echo -e "# Updating Operating System #"
echo -e "#############################\e[0m"
echo ""
echo ""
apt update && apt upgrade -y
echo ""
echo ""
echo -e "\e[32m#############################"
echo -e "#     Done With Upgrade     #"
echo -e "#############################\e[0m"
echo ""
echo ""
echo -e "\e[32m#############################"
echo -e "#  Starting Dist-Upgrade    #"
echo -e "#############################\e[0m"
echo ""
echo ""
apt full-upgrade -y
echo ""
echo ""
echo -e "\e[32m#############################"
echo -e "#  Operating System Updated #"
echo -e "#############################\e[0m"
echo ""
echo ""
