#!/bin/bash

echo "ubuntu-update.sh Copyright (C) 2018 Ted LeRoy"
echo "This program comes with ABSOLUTELY NO WARRANTY' see "
echo " https://github.com/TedLeRoy/ubuntu-update.sh/blob/master/LICENSE.md"
echo "This is free software, and you are welcome to redistribute it"
echo "under certain conditions."
echo "Again, see  https://github.com/TedLeRoy/ubuntu-update.sh/blob/master/LICENSE.md"
echo "for details."

echo ""
echo ""
echo "#############################"
echo "# Updating Operating System #"
echo "#############################"
echo ""
echo ""
apt update && apt upgrade -y
echo ""
echo ""
echo "#############################"
echo "#     Done With Upgrade     #"
echo "#############################"
echo ""
echo ""
echo "#############################"
echo "#  Starting Dist-Upgrade    #"
echo "#############################"
echo ""
echo ""
apt full-upgrade -y
echo ""
echo ""
echo "#############################"
echo "#  Operating System Updated #"
echo "#############################"
echo ""
echo ""
