#!/bin/bash

echo ""
echo ""
echo "#############################"
echo "# Updating Operating System #"
echo "#############################"
echo ""
echo ""
apt update && apt upgrade -y
echo ""
echo ""
echo "#############################"
echo "#     Done With Upgrade     #"
echo "#############################"
echo ""
echo ""
echo "#############################"
echo "#  Starting Dist-Upgrade    #"
echo "#############################"
echo ""
echo ""
apt full-upgrade -y
echo ""
echo ""
echo "#############################"
echo "#  Operating System Updated #"
echo "#############################"
echo ""
echo ""
